Repository Ontotext-AD/graphdb-workbench, pull requests merged in 2019-11, with the labels that each got.

#132 Fix code snippet in dev guide
  docs/developers-guide.md
Labels: documentation

#131 Cypress tests stabilization
  test-cypress/integration/explore/similarity.spec.js
  test-cypress/integration/sparql/sparql.menu.spec.js
  test-cypress/support/sparql-commands.js
Labels: testing

#135 Gdb 4034 create shacl repo in workbench
  package-lock.json
  package.json
  src/pages/repository.html
  test-cypress/package-lock.json
  test-cypress/package.json
Labels: enhancement

#134 Fix ui related issues
  src/app.js
  src/css/rdf-details-side-panel.css
  src/pages/domainRangeInfo.html
  src/pages/graphs-visualizations.html
  src/pages/rdfClassHierarchyInfo.html
Labels: bug

#138 Enable sonar analysis again
  .travis.yml
Labels: configuration

#140 GDB-4078 Changed style in filesTable.html and query-editor.html to pr…
  src/css/import.css
Labels: enhancement

#143 Prepare 1.2.0-TR4
  package-lock.json
  package.json
  test-cypress/package-lock.json
  test-cypress/package.json
Labels: release

#148 GDB-4100 fix cannot create custom graph
  src/js/angular/graphexplore/app.js
  src/pages/graph-config/saveGraphConfig.html
  src/pages/graphs-visualizations.html
  test-cypress/integration/explore/visual.graph.spec.js
Labels: bug
